apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Maverickme222222/argo-all.git
    path: core
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
