apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- disallow-privileged-containers.yaml
- restrict-loadbalancer.yaml
- disallow-capabilities.yaml
- restrict-escalation-verbs-roles.yaml
- restrict-wildcard-verbs.yaml
- restrict-wildcard-resources.yaml
- enforce-sidecar-injection-namespace.yaml
- enforce-strict-mtls.yaml
- baseline-latest.yaml
- disallow_secrets_from_env_vars.yaml
namespace: kyverno