apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: skip-istio-init-pod-validation
spec:
  background: true
  rules:
    - name: skip-istio-init-pod
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - default
      preconditions:
        any:
        - key: "istio-init"
          operator: NotIn
          value: "{{ images.initContainers.*.name }}"
      validate:
        message: >-
          skip istio init pod.