apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: core/argo-workflows/overlays/production
    repoURL: https://github.com/Maverickme222222/argo-all.git
    targetRevision: HEAD
  destination:
    namespace: argo-workflows
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

