apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-resources
  namespace: argocd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    path: core/kyverno-resources/overlays/production
    repoURL: https://github.com/Maverickme222222/argo-all.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
